
package integradora.segundo.cuatrimestre;

import java.util.ArrayList;
import static javax.swing.JOptionPane.*;

public class MenuInventario extends javax.swing.JFrame {

    // <editor-fold defaultstate="collapsed" desc="Metodos Obtener">
    public String ObtenerSeccion(){
        return Seccion.getSelectedItem().toString();
    }
    // </editor-fold>
    
    /**
     * Creates new form InventarioProductos
     */
    public MenuInventario() {
        initComponents();
        
        for (String seccion: Main.inv.Secciones)
            Seccion.addItem(seccion);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ActivarAgregarProducto = new javax.swing.JRadioButton();
        PanelInvetario = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoPrincipal = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Seccion = new javax.swing.JComboBox<>();
        Objetos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        BackToMenu = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ActivarInventario = new javax.swing.JRadioButton();
        PanelAgregarProducto = new java.awt.Panel();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        SeccionComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ActivarAgregarProducto.setText("Agregar Productos");
        ActivarAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivarAgregarProductoActionPerformed(evt);
            }
        });

        TextoPrincipal.setEditable(false);
        TextoPrincipal.setColumns(20);
        TextoPrincipal.setRows(5);
        TextoPrincipal.setText("Nombre del producto: tal\nUnidades: tantas\nPropiedad 1: x\nPropiedad 2: y\nPropiedad 3: z\n\nNotas: este es un producto, increible");
        jScrollPane1.setViewportView(TextoPrincipal);

        jLabel1.setText("Seccion");

        Seccion.setSelectedIndex(-1);
        Seccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeccionMouseClicked(evt);
            }
        });
        Seccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeccionActionPerformed(evt);
            }
        });

        Objetos.setMaximumSize(new java.awt.Dimension(256, 256));
        Objetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjetosActionPerformed(evt);
            }
        });

        jLabel2.setText("Objeto");

        BackToMenu.setText("Menu");
        BackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuActionPerformed(evt);
            }
        });

        jButton2.setText("Accion 1");

        jButton3.setText("Accion 2");

        jButton4.setText("Accion 3");

        javax.swing.GroupLayout PanelInvetarioLayout = new javax.swing.GroupLayout(PanelInvetario);
        PanelInvetario.setLayout(PanelInvetarioLayout);
        PanelInvetarioLayout.setHorizontalGroup(
            PanelInvetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInvetarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInvetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInvetarioLayout.createSequentialGroup()
                        .addGroup(PanelInvetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(PanelInvetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Objetos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(PanelInvetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(BackToMenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelInvetarioLayout.setVerticalGroup(
            PanelInvetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInvetarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelInvetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInvetarioLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(PanelInvetarioLayout.createSequentialGroup()
                        .addGroup(PanelInvetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelInvetarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Objetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Objetos.getAccessibleContext().setAccessibleName("");

        ActivarInventario.setSelected(true);
        ActivarInventario.setText("Habilitar");
        ActivarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivarInventarioActionPerformed(evt);
            }
        });

        PanelAgregarProducto.setEnabled(false);

        jButton6.setText("Agregar");

        jTextField1.setText("Nombre");

        jLabel3.setLabelFor(jTextField1);
        jLabel3.setText("Nombre");

        jLabel4.setText("Unidades");
        jLabel4.setToolTipText("");

        jTextField2.setText("Unidades");

        SeccionComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Productos", "Electronicos" }));
        SeccionComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeccionComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Seccion");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout PanelAgregarProductoLayout = new javax.swing.GroupLayout(PanelAgregarProducto);
        PanelAgregarProducto.setLayout(PanelAgregarProductoLayout);
        PanelAgregarProductoLayout.setHorizontalGroup(
            PanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(SeccionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAgregarProductoLayout.setVerticalGroup(
            PanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgregarProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeccionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ActivarAgregarProducto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PanelAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelInvetario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ActivarInventario, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ActivarInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelInvetario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActivarAgregarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeccionActionPerformed
        // <editor-fold defaultstate="collapsed" desc="Obtener la seccion"> 
        String opcion = null;
        
        // 2025 Feb 12: Esto esta en un bloque try catch por que esto se llama al inicio de cuando se corre el codigo
        // Antes de que se le agreguen sus secciones, cosa que causa errores
        try {
            opcion = Seccion.getSelectedItem().toString();
        } catch (Exception e) { return; }
        // </editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Agregar los elementos"> 
        Objetos.removeAllItems();
        try { 
            ArrayList<String> elementos = new ArrayList<>();
            
            for (Inventario.Elemento elemento : Main.inv.Inventario.get(opcion))
                Objetos.addItem(elemento.Nombre);
        } catch (Exception e) {
            System.out.println("Hubo un error al intentar acceder: " + opcion);
            showMessageDialog(null, "Hubo un error al intentar acceder " + opcion, "Error", ERROR_MESSAGE);
            Objetos.addItem("error");
        }
        // </editor-fold>
    }//GEN-LAST:event_SeccionActionPerformed

    private void BackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BackToMenuActionPerformed

    private void ActivarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivarInventarioActionPerformed
        if (PanelInvetario.isEnabled()){
            PanelInvetario.setEnabled(false);
        } else {
            PanelInvetario.setEnabled(true);
        }
    }//GEN-LAST:event_ActivarInventarioActionPerformed

    private void ActivarAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivarAgregarProductoActionPerformed
        if (PanelAgregarProducto.isEnabled()){
            PanelAgregarProducto.setEnabled(false);
        }
        else{
            PanelAgregarProducto.setEnabled(true);
        }
    }//GEN-LAST:event_ActivarAgregarProductoActionPerformed

    private void SeccionComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeccionComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeccionComboBox1ActionPerformed

    private void SeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeccionMouseClicked
        // 2025 Feb 10: No puedo borrar esto . . .
    }//GEN-LAST:event_SeccionMouseClicked

    private void ObjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjetosActionPerformed
        // <editor-fold defaultstate="collapsed" desc="Obtener la seccion"> 
        String objeto = null;
        
        // 2025 Feb 12: Esto esta en un bloque try catch por que esto se llama al inicio de cuando se corre el codigo
        // Antes de que se le agreguen sus secciones, cosa que causa errores
        try {
            objeto = Objetos.getSelectedItem().toString();
        } catch (Exception e) { return; }
        // </editor-fold>
        
        TextoPrincipal.selectAll();
        TextoPrincipal.replaceSelection(null);
        TextoPrincipal.insert(Main.inv.Encontrar(Seccion.getSelectedItem().toString(), objeto).toString(), 0);
    }//GEN-LAST:event_ObjetosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ActivarAgregarProducto;
    private javax.swing.JRadioButton ActivarInventario;
    private javax.swing.JButton BackToMenu;
    private javax.swing.JComboBox<String> Objetos;
    private java.awt.Panel PanelAgregarProducto;
    private java.awt.Panel PanelInvetario;
    private javax.swing.JComboBox<String> Seccion;
    private javax.swing.JComboBox<String> SeccionComboBox1;
    private javax.swing.JTextArea TextoPrincipal;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
